version: '2.1'
services:

### Application Code Container

  munchkincounter_application:
      container_name: munchkincounter_app
#you can comment out the next line
      restart: always
      build: .
      image: munchkincounter/munchkincounter_app
      ports:
# change the local-port
# [local-ip]:[local-port]:[container-port]
          - "127.0.0.1:8000:80"
